services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=${SERVER_IP} # optional, autodiscovery response domain or IP address.
    volumes:
      - ./config/:/config
      - /srv/dockerdata/media_server/media:/data
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 7359:7359/udp # optional, Allows clients to discover Jellyfin on the local network.
      - 1900:1900/udp # optional, Service discovery used by DNLA and clients.
    restart: unless-stopped
    networks:
      - main_default

networks:
  main_default:
    external: true
